import re
x='My  2 fav numbers for 69 and 420'
a=re.findall('\S+[aeiou]+\S',x)
b=re.findall('[aeiou]',x)
c=re.findall('\S+[a-z]+\S',x)
d=re.findall('[0-9]+',x)
print('a=',a)
print('b=',b)
print('c=',c)
print('d=',d)
y='From: Using the : chacacter'
z='From atharv.5873@gmail.com Sat Mar 13 09:43:23 1997' 
e=re.findall('^F.+:',y)#Greedy Ma   tching
f=re.findall('^F.+?:',y)#Non-Greedy Matching 
print('e=',e)
print('f=',f)
g=re.findall('\S+@\S+',z)
h=re.findall('@([^ ]*)',z)
print('g=',g)
print('h=',h)